spring.application.name=goodreads
spring.datasource.url = jdbc:h2:file:C:/Users/GOPI SAI/Documents/GitHub/good-reads-application/src/main/goodreads
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update